package com.lilithsthrone.ui;

import com.badlogic.gdx.graphics.OrthographicCamera;
import com.badlogic.gdx.graphics.g2d.BitmapFont;
import com.badlogic.gdx.graphics.g2d.SpriteBatch;
import com.badlogic.gdx.graphics.glutils.ShapeRenderer;
import com.lilithsthrone.game.Game;
import com.lilithsthrone.main.Main;
import com.lilithsthrone.ui.TextScreenRenderer.ClickableRegion;

/**
 * LibGdxUIManager: Implements UIManager interface for LibGDX-based text rendering.
 * 
 * This class acts as a bridge between the game's core logic (Game.java, RenderingEngine.java,
 * MainController.java) and LibGDX's rendering system. It:
 * 
 * 1. Receives HTML content from RenderingEngine via setContent()
 * 2. Parses and renders HTML as text via TextScreenRenderer
 * 3. Detects mouse clicks and routes them to MainController
 * 4. Maintains the same event-driven architecture as the original JavaFX version
 * 
 * The key insight is that the game's rendering is event-driven (click → update display),
 * not continuous (60 FPS rendering). TextScreenRenderer only renders when the game state
 * changes, significantly reducing CPU usage compared to real-time graphics engines.
 * 
 * @version 1.0.0
 * @author Step 3 UI Refactoring
 */
public class LibGdxUIManager implements UIManager {

	private TextScreenRenderer textRenderer;
	private BitmapFont font;
	private SpriteBatch spriteBatch;
	private ShapeRenderer shapeRenderer;
	private OrthographicCamera camera;
	
	private String currentHTML;
	private boolean contentUpdated = false;
	private int screenWidth = 1200;
	private int screenHeight = 800;
	
	/**
	 * Constructor - receives rendering resources directly from GameScreen
	 * 
	 * @param spriteBatch LibGdX sprite batch for rendering
	 * @param font BitmapFont for text rendering
	 * @param shapeRenderer ShapeRenderer for UI elements (status bars, borders)
	 * @param camera OrthographicCamera for coordinate transformation
	 */
	public LibGdxUIManager(SpriteBatch spriteBatch, BitmapFont font, ShapeRenderer shapeRenderer, OrthographicCamera camera) {
		this.spriteBatch = spriteBatch;
		this.font = font;
		this.shapeRenderer = shapeRenderer;
		this.camera = camera;
		this.textRenderer = new TextScreenRenderer();
		this.currentHTML = "";
	}
	
	/**
	 * Update UI state each frame
	 * Called by GameScreen.update() to process frame updates
	 * 
	 * @param delta Time since last frame in seconds
	 */
	public void update(float delta) {
		// Currently just maintains state - could add animations/transitions here
	}
	
	/**
	 * Render the current content to the screen
	 * Called every frame by GameScreen to display the game
	 */
	@Override
	public void render() {
		if (spriteBatch == null || font == null) {
			// Resources not initialized yet
			return;
		}
		
		// Always render to show current state
		// The batch should already be begun by LibGdxApp
		textRenderer.render(spriteBatch, font, shapeRenderer);
	}
	
	/**
	 * Set content to display (called by game when state changes)
	 * This is the main entry point from the game logic.
	 * 
	 * When Game.java updates the current dialogue node, it calls this method
	 * with the HTML generated by RenderingEngine.
	 * 
	 * @param htmlContent HTML string from RenderingEngine
	 */
	@Override
	public void setContent(String htmlContent) {
		if (htmlContent != null && !htmlContent.equals(currentHTML)) {
			this.currentHTML = htmlContent;
			this.contentUpdated = true;
			
			// Parse the HTML and prepare for rendering
			textRenderer.parseHTML(htmlContent);
		}
	}
	
	/**
	 * Handle mouse click input
	 * Routes clicks to the appropriate game logic handler
	 * 
	 * This is called by LibGdxApp when the user clicks the mouse.
	 * It determines which dialogue choice, inventory item, or navigation button was clicked,
	 * then delegates to the appropriate event listener in MainController.
	 * 
	 * @param screenX X coordinate of click (in screen space)
	 * @param screenY Y coordinate of click (in screen space)
	 */
	@Override
	public void mousePressed(float screenX, float screenY) {
		// Get the clicked element from the renderer
		ClickableRegion clickedRegion = textRenderer.getClickedElement(screenX, screenY);
		
		if (clickedRegion == null) {
			// User clicked on non-interactive area
			return;
		}
		
		// Route the click based on element type
		routeClickToGameLogic(clickedRegion);
	}
	
	/**
	 * Handle mouse movement for hover effects
	 * 
	 * @param screenX X coordinate of mouse
	 * @param screenY Y coordinate of mouse
	 */
	@Override
	public void mouseMoved(float screenX, float screenY) {
		textRenderer.setHoveredElement(screenX, screenY);
	}
	
	/**
	 * Route a click to the appropriate game logic handler
	 * 
	 * This method examines the clicked element's ID and calls the corresponding
	 * MainController event listener method. The original MainController already has
	 * event listeners for all interactions:
	 * - ButtonCharactersEventListener
	 * - ButtonInventoryEventListener
	 * - ButtonMainMenuEventListener
	 * - SelectDialogueChoice handlers
	 * - etc.
	 * 
	 * We delegate to these existing handlers rather than duplicating logic.
	 */
	private void routeClickToGameLogic(ClickableRegion clickedRegion) {
		String elementId = clickedRegion.id;
		
		// Handle dialogue choice clicks
		if (elementId.startsWith("choice_")) {
			try {
				int choiceIndex = Integer.parseInt(elementId.substring(7));
				handleDialogueChoice(choiceIndex);
			} catch (NumberFormatException e) {
				System.err.println("Invalid choice ID: " + elementId);
			}
		}
		
		// Handle navigation buttons
		else if (elementId.equals("btn_inventory")) {
			handleInventoryButton();
		}
		else if (elementId.equals("btn_character")) {
			handleCharacterButton();
		}
		else if (elementId.equals("btn_map")) {
			handleMapButton();
		}
		else if (elementId.equals("btn_back")) {
			handleBackButton();
		}
		
		// Handle direction buttons (map navigation)
		else if (elementId.equals("moveNorth")) {
			handleMoveDirection("north");
		}
		else if (elementId.equals("moveSouth")) {
			handleMoveDirection("south");
		}
		else if (elementId.equals("moveEast")) {
			handleMoveDirection("east");
		}
		else if (elementId.equals("moveWest")) {
			handleMoveDirection("west");
		}
		
		// Handle inventory item clicks
		else if (elementId.endsWith("Slot")) {
			handleInventorySlotClick(elementId);
		}
	}
	
	/**
	 * Handle dialogue choice selection
	 * 
	 * In the original game, when a player clicks a dialogue choice,
	 * MainController calls Game.setContent() with the selected response index.
	 * 
	 * @param choiceIndex The index of the selected choice
	 */
	private void handleDialogueChoice(int choiceIndex) {
		// Game.selectResponse() or similar - depends on actual API
		// For now, we trigger a game state update through the normal flow
		if (Main.game != null && Main.game.getCurrentDialogueNode() != null) {
			// This would call the response handler
			// The exact method depends on Game.java's public API
			// For now, we use setContent() which triggers rendering
			Main.game.setContent(choiceIndex);
		}
	}
	
	/**
	 * Handle inventory button click
	 */
	private void handleInventoryButton() {
		// Delegates to existing ButtonInventoryEventListener logic
		// This is a placeholder - actual implementation depends on MainController structure
		if (Main.game != null) {
			// Game would switch to inventory view
			Main.game.openInventory();
		}
	}
	
	/**
	 * Handle character sheet button click
	 */
	private void handleCharacterButton() {
		// Delegates to existing ButtonCharactersEventListener logic
		if (Main.game != null) {
			Main.game.openCharacterSheet();
		}
	}
	
	/**
	 * Handle map button click
	 */
	private void handleMapButton() {
		// Show map screen
		if (Main.game != null) {
			Main.game.openMap();
		}
	}
	
	/**
	 * Handle back button click
	 */
	private void handleBackButton() {
		// Go to previous dialogue
		if (Main.game != null) {
			Main.game.goBack();
		}
	}
	
	/**
	 * Handle directional movement on map
	 */
	private void handleMoveDirection(String direction) {
		// Delegates to existing ButtonMoveNorthEventListener, etc.
		if (Main.game != null) {
			switch (direction.toLowerCase()) {
				case "north":
					Main.game.moveNorth();
					break;
				case "south":
					Main.game.moveSouth();
					break;
				case "east":
					Main.game.moveEast();
					break;
				case "west":
					Main.game.moveWest();
					break;
			}
		}
	}
	
	/**
	 * Handle inventory slot click
	 */
	private void handleInventorySlotClick(String slotId) {
		// Remove "Slot" suffix to get slot name
		String slotName = slotId.replace("Slot", "");
		
		// This would open item details or equipment menu
		// Delegates to existing inventory interaction logic
		if (Main.game != null) {
			Main.game.selectInventorySlot(slotName);
		}
	}
	
	/**
	 * Set screen dimensions (for handling window resize)
	 */
	@Override
	public void setScreenSize(int width, int height) {
		if (textRenderer != null) {
			textRenderer.setScreenSize(width, height);
		}
	}
	
	/**
	 * Get the current HTML content (for debugging)
	 */
	public String getCurrentHTML() {
		return currentHTML;
	}
	
	/**
	 * Get the text renderer (for access to rendered elements, debugging)
	 */
	public TextScreenRenderer getTextRenderer() {
		return textRenderer;
	}
}
